import axios from "axios";
export default async function postQuestion(userid:string,survey:string,finalscore:number,value:any){
    const ComURL='http://localhost:3500/communication/'
    const discURL='http://localhost:3500/Disscovery'
    const designURL='http://localhost:3500/Design'
    const delivURL='http://localhost:3500/Delivery'
    const stakeURL='http://localhost:3500/Stakeholder'
    const visionURL='http://localhost:3500/Vision'
    const knowlURL='http://localhost:3500/IndustryKnwlg'
    
    if(survey=='1'){
        axios.patch(ComURL,{
        user:userid,
        Collaboration:finalscore,
        CollabAnswr:value
    }
        )
    }
    if(survey=='2'){
        axios.patch(ComURL,{
        user:userid,
        Communication:finalscore,
        CommunAnswr:value
    }
        )
    }
    if(survey=='3'){
        axios.patch(ComURL,{
        user:userid,
        Quality:finalscore,
        QualitAnswr:value
    }
        )
    }
    if(survey=='4'){
        axios.patch(ComURL,{
        user:userid,
        DecisionMaking:finalscore,
        DecisionAnswr:value
    }
        )
    }
    if(survey=='5'){
        axios.patch(ComURL,{
        user:userid,
        Learning:finalscore,
        LearningAnswr:value
    }
        )
    }
    if(survey=='6'){
        axios.patch(ComURL,{
        user:userid,
        Organisational:finalscore,
        OrganizationAnswr:value
    }
        )
    }
    if(survey=='7'){
        axios.patch(ComURL,{
        user:userid,
        Bias:finalscore,
        BiasAnswr:value
    }
        )
    }
    if(survey=='8'){
        axios.patch(discURL,{
        user:userid,
        UserResearch:finalscore,
        UserResearchAnswr:value
    }
        )
    }
    if(survey=='9'){
        axios.patch(discURL,{
        user:userid,
        Design:finalscore,
        DesignAnswr:value
    }
        )
    }
    if(survey=='10'){
        axios.patch(discURL,{
        user:userid,
        Market:finalscore,
        MarketAnswr:value
    }
        )
    }
    if(survey=='11'){
        axios.patch(discURL,{
        user:userid,
        Synthesising:finalscore,
        SynthesisingAnswr:value
    }
        )
    }
    if(survey=='12'){
        axios.patch(designURL,{
        user:userid,
        Product:finalscore,
        ProductAnswr:value
    }
        )
    }
    if(survey=='13'){
        axios.patch(designURL,{
        user:userid,
        Visual:finalscore,
        VisualAnswr:value
    }
        )
    }
    if(survey=='14'){
        axios.patch(designURL,{
        user:userid,
        UXDesign:finalscore,
        UXDesignAnswr:value
    }
        )
    }
    if(survey=='15'){
        axios.patch(designURL,{
        user:userid,
        UXTesting:finalscore,
        UXTestingAnswr:value
    }
        )
    }
    if(survey=='16'){
        axios.patch(delivURL,{
        user:userid,
        Business:finalscore,
        BusinessAnswr:value
    }
        )
    }
    if(survey=='17'){
        axios.patch(delivURL,{
        user:userid,
        Product:finalscore,
        ProductAnswr:value
    }
        )
    }
    if(survey=='18'){
        axios.patch(delivURL,{
        user:userid,
        Technology:finalscore,
        TechnologyAnswr:value
    }
        )
    }
    if(survey=='19'){
        axios.patch(delivURL,{
        user:userid,
        Agile:finalscore,
        AgileAnswr:value
    }
        )
    }
    if(survey=='20'){
        axios.patch(stakeURL,{
        user:userid,
        Engagement:finalscore,
        EngagementAnswr:value
    }
        )
    }
    if(survey=='21'){
        axios.patch(stakeURL,{
        user:userid,
        Leadership:finalscore,
        LeadershipAnswr:value
    }
        )
    }
    if(survey=='22'){
        axios.patch(stakeURL,{
        user:userid,
        Management:finalscore,
        ManagementAnswr:value
    }
        )
    }
    if(survey=='23'){
        axios.patch(visionURL,{
        user:userid,
        Vision:finalscore,
        VisionAnswr:value
    }
        )
    }
    if(survey=='24'){
        axios.patch(visionURL,{
        user:userid,
        Strategy:finalscore,
        StrategyAnswr:value
    }
        )
    }
    if(survey=='25'){
        axios.patch(visionURL,{
        user:userid,
        RoadMapping:finalscore,
        RoadMappingAnswr:value
    }
        )
    }
    if(survey=='26'){
        axios.patch(knowlURL,{
        user:userid,
        General:finalscore,
        GeneralAnswr:value
    }
        )
    }
    if(survey=='27'){
        axios.patch(knowlURL,{
        user:userid,
        Specific:finalscore,
        SpecificAnswr:value
    }
        )
    }

   
   
    }