export const titlesCom=[
    '',
    'Working with a team',
    'Communication and articulation',
    'Quality of work and reliability',
    'Decision making',
    'Continuous learning',
    'Organisational skills',
    'Bias to Action',
    'User Research',
    'Design thinking',
    'Market Research',
    'Synthesising findings',
    'Product thinking',
    'Visual Design',
    'UX & Interaction design',
    'UX testing',
    


]
export const titles1=[
    'Working with a team',
    'Communication and articulation',
    'Quality of work and reliability',
    'Decision making',
    'Continuous learning',
    'Organisational skills',
    'Bias to Action',
    'User Research',
    'Design thinking',
    'Market Research',
    'Synthesising findings',
    'Product thinking',
    'Visual Design',
    'UX & Interaction design',
    'UX testing',
    


]
export const titles2=[
    'Business Process Management',
    'Product Development',
    'Technology Awareness',
    'Agile Product Delivery',
    'Engagement',
    'Leadership',
    'Stakeholder Management',
    'Vision',
    'Strategy',
    'Road Mapping',
    'General Industry knowledge',
    'Industry specific processes',
]
export const discription =[
    '',
'The ability to collaborate with others and facilitate collaboration with and between colleagues',
'The skills in written, verbal and non-verbal communication',
'The quality of being trustworthy or of performing consistently well',
'The ability to and the action of making important decisions',
"The conscious knowledge of one's own character and competencies and the drive to improve",
"Coordinating own and colleagues' activities in order to sustain and reach business value",
'Getting stuff done',
'Understand customer needs & product success qualitatively and quantitatively',
'',
'Awareness of the market size and segments, customer mix, competitors, trends and gaps',
'The ability to understand and interpret the research findings into a tangible concept that takes advantage of an opportunity discovered and validated during research',
"",
'Creating products that provide meaningful and relevant experiences to users',
'A testing method for measuring how easy and user-friendly a software application is',
'Business process management (BPM) is the discipline in which people use various methods to discover, model, analyze, measure, improve and optimize business processes',
'Bringing the product from concept to launch',
'Awareness of how software works',
'Equipping delivery team and supporting their effectiveness',
'Building collaboration & engagement across a team and within an organization',
'Acting as a Product leader',
'Managing key stakeholders & clients across the Organization',
'Understanding the vision for your Product',
'Turning visions into plans',
'Able to define and build strategy across a business',
'Terminology, Company types, roles in the company',
'Key and supportive processes needed to run a compliant and successful business'
]

